/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BriefIntroductionCard: typeof import('./src/components/brief-introduction-card.vue')['default']
    Collapse: typeof import('./src/components/collapse.vue')['default']
    DetailSwiper: typeof import('./src/components/detail-swiper.vue')['default']
    IconCustomSearch: typeof import('~icons/custom/search')['default']
    ProductCard: typeof import('./src/components/product-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonComponent: typeof import('./src/components/skeleton-component.vue')['default']
    PosterBanner: typeof import('./src/layout/posterBanner.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Swiper: typeof import('./src/components/swiper.vue')['default']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSkeletonImage: typeof import('vant/es')['SkeletonImage']
    VanSkeletonParagraph: typeof import('vant/es')['SkeletonParagraph']
  }
}
