/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BriefIntroductionCard: typeof import('./components/brief-introduction-card.vue')['default']
    Collapse: typeof import('./components/collapse.vue')['default']
    DetailSwiper: typeof import('./components/detail-swiper.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ImagePreview: typeof import('./components/GlobalPreview/ImagePreview.vue')['default']
    PcDetailSwiper: typeof import('./components/pc-detail-swiper.vue')['default']
    Privacy: typeof import('./components/privacy.vue')['default']
    ProductCard: typeof import('./components/product-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonComponent: typeof import('./components/skeleton-component.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    Swiper: typeof import('./components/swiper.vue')['default']
  }
}

// For TSX support
declare global {
  const BriefIntroductionCard: typeof import('./components/brief-introduction-card.vue')['default']
  const Collapse: typeof import('./components/collapse.vue')['default']
  const DetailSwiper: typeof import('./components/detail-swiper.vue')['default']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ImagePreview: typeof import('./components/GlobalPreview/ImagePreview.vue')['default']
  const PcDetailSwiper: typeof import('./components/pc-detail-swiper.vue')['default']
  const Privacy: typeof import('./components/privacy.vue')['default']
  const ProductCard: typeof import('./components/product-card.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SkeletonComponent: typeof import('./components/skeleton-component.vue')['default']
  const SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  const Swiper: typeof import('./components/swiper.vue')['default']
}