/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BriefIntroductionCard: typeof import('./components/brief-introduction-card.vue')['default']
    Collapse: typeof import('./components/collapse.vue')['default']
    DetailSwiper: typeof import('./components/detail-swiper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    PcDetailSwiper: typeof import('./components/pc-detail-swiper.vue')['default']
    Privacy: typeof import('./components/privacy.vue')['default']
    ProductCard: typeof import('./components/product-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./components/h5/SearchModal.vue')['default']
    SkeletonComponent: typeof import('./components/skeleton-component.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    Swiper: typeof import('./components/swiper.vue')['default']
  }
}
